name: json_matcher
version: 0.2.4
homepage: https://github.com/f3ath/json-matcher
description: "JSON Matchers for unit tests: encodesToJson() checks if the value encodes to expected JSON, isJson() checks if the string is expected JSON."
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  convert: ^3.1.1
  matcher: ^0.12.14
dev_dependencies:
  test: ^1.21.3
